version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: printer-server_server_1
      APP_PORT: 631

  server:
    image: ydkn/cups:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    ports:
      - "${APP_PORT:-8097}:631"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/cups
